FROM registry.cn-hangzhou.aliyuncs.com/xvjialing/image_identification:base

# Install python 3.7.3
RUN apt-get update \
  && apt-get -yqq install --no-install-recommends \
  wget \
  build-essential \
  g++ \
  python3-dev \
  python3-pip \
  python3-venv
  
# install pytorch  
RUN pip install --upgrade setuptools \
 && pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl \
 && pip3 install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
  
# install python
RUN pip3 install flask Flask-Cors tensorflow==1.13.1 tensorflow-serving-api==1.13.0 xmlrunner
